spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/memory-schema?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: memory-user
    password: memory*1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: secret
